---
# This is an example playbook to execute Ansible tests.
- name: Uninstall | Verify
  hosts: all
  gather_facts: true
  tasks:

    - name: Verify | Include vars
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - ../../defaults/main.yml
        - ./variables.yml
        - "../../defaults/{{ ansible_os_family|lower }}.yml"

    - name: Verify | Deploy package
      become: true
      ansible.builtin.package:
        name: "{{ item }}"
        state: "{{ git_package_state }}"
      register: _verify_package_installed
      failed_when:
        - (
          (_verify_package_installed is changed) or
          (_verify_package_installed is failed)
          )
      loop: "{{ git_package_name }}"
