---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: fedora32
    image: geerlingguy/docker-fedora32-ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    pre_build_image: true
  - name: fedora33
    image: geerlingguy/docker-fedora33-ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    pre_build_image: true
  - name: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
scenario:
  name: default
  test_sequence:
    #    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: ansible
# lint: |
#   set -e
#   yamllint .
#   ansible-lint .
